zuihou:
  log:
    enabled: true
  port:
    nginx: ${server.port}
    eureka: 8761
  ip:
    mysql: ${MYSQL_HOST:${spring.cloud.client.ip-address}}
    nginx: ${NGINX_HOST:${spring.cloud.client.ip-address}}
    eureka: ${EUREKA_HOST:${spring.cloud.client.ip-address}}
  mysql:
    authority:
      database: zuihou_authority_dev
    port: 3306
    username: root
    password: root

