zuihou:
  ip:
    mysql: ${MYSQL_HOST:192.168.1.34}
  mysql:
    database: zuihou_jobs_dev
    port: 3306
    username: root
    password: root

server:
  port: 8080
spring:
  profiles:
    active: docker