zuihou:
  port:
    nginx: ${NGINX_PORT:${server.port}}
    eureka: ${EUREKA_PORT:8761}
  ip:
    mysql: ${MYSQL_IP:${spring.cloud.client.ip-address}}
    nginx: ${NGINX_IP:${spring.cloud.client.ip-address}}
    eureka: ${EUREKA_IP:${spring.cloud.client.ip-address}}
  mysql:
    demo:
      database: zuihou_demo_dev       # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: root

logging:
  io.seata: debug
  org.springframework.cloud.alibaba.seata.web: debug
