zuihou:
  port:
    nginx: ${NGINX_PORT:80}
    eureka: ${EUREKA_PORT:8761}
  ip:
    nginx: ${NGINX_IP:${spring.cloud.client.ip-address}}
    eureka: ${EUREKA_IP:${spring.cloud.client.ip-address}}
  context-path:
    eureka: /zuihou-eureka
  variable:
    gate-way-url-prefix: http://127.0.0.1:9970

shiro:
  realm: com.github.zuihou.center.shiro.ShiroAuthorizingRealm
  loginUrl: http://center.zuihou.com:${server.port}/login
  successUrl: http://center.zuihou.com:${server.port}/index
  unauthorizedUrl: http://center.zuihou.com:${server.port}/unauthorized
  filterChainDefinitions:
    anon:
      - /login
      - /register
      - /static/**
      - /actuator/**
      - /webjars/**
    logout:
      - /logout
    authc:
      /**

server:
  port: 8766
  servlet:
    context-path: /zuihou-center

spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .html
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    status-page-url: http://${zuihou.ip.nginx}:${zuihou.port.nginx}${server.servlet.context-path}${spring.mvc.servlet.path:}
    status-page-url-path: ${server.servlet.context-path:}${spring.mvc.servlet.path:}${management.endpoints.web.base-path:}/info
    health-check-url-path: ${server.servlet.context-path:}${spring.mvc.servlet.path:}${management.endpoints.web.base-path:}/health
    home-page-url-path: ${server.servlet.context-path:}${spring.mvc.servlet.path:}
    preferIpAddress: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}${server.context-path:}
    metadata-map:
      user.name: ${spring.security.user.name:}
      user.password: ${spring.security.user.password:}
      management.context-path: ${server.servlet.context-path:}${spring.mvc.servlet.path:}${management.endpoints.web.base-path:}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name:}:${spring.security.user.password:}@${zuihou.ip.eureka}:${zuihou.port.eureka}${zuihou.context-path.eureka}/eureka/

